"""initial migration

Revision ID: cacc3dc0382a
Revises: 
Create Date: 2023-04-01 14:14:00.966426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacc3dc0382a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_heroes',
    sa.Column('id_heroes', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_heroes'),
    sa.UniqueConstraint('name')
    )
    op.create_table('db_links',
    sa.Column('id_links', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_links')
    )
    op.create_table('db_heroes_info',
    sa.Column('id_heroes_info', sa.Integer(), nullable=False),
    sa.Column('heroes_id', sa.Integer(), nullable=True),
    sa.Column('class_heroes', sa.Integer(), nullable=False),
    sa.Column('meta', sa.Integer(), nullable=False),
    sa.Column('is_alliance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['heroes_id'], ['db_heroes.id_heroes'], ),
    sa.PrimaryKeyConstraint('id_heroes_info')
    )
    op.create_table('db_stats',
    sa.Column('id_Stats', sa.Integer(), nullable=False),
    sa.Column('heroes_id', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('magic_resistance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['heroes_id'], ['db_heroes.id_heroes'], ),
    sa.PrimaryKeyConstraint('id_Stats')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_stats')
    op.drop_table('db_heroes_info')
    op.drop_table('db_links')
    op.drop_table('db_heroes')
    # ### end Alembic commands ###
